/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FragranceSlugRouteImport } from './routes/fragrance.$slug'
import { Route as ApiPublicHooksAbandonedCartSweepRouteImport } from './routes/api/public/hooks/abandoned-cart-sweep'
import { Route as ApiPublicHooksShipmentRouteImport } from './routes/api/public/hooks/shipment'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FragranceSlugRoute = FragranceSlugRouteImport.update({
  id: '/fragrance/$slug',
  path: '/fragrance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAbandonedCartSweepRoute =
  ApiPublicHooksAbandonedCartSweepRouteImport.update({
    id: '/api/public/hooks/abandoned-cart-sweep',
    path: '/api/public/hooks/abandoned-cart-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShipmentRoute = ApiPublicHooksShipmentRouteImport.update({
  id: '/api/public/hooks/shipment',
  path: '/api/public/hooks/shipment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fragrance/$slug': typeof FragranceSlugRoute
  '/api/public/hooks/abandoned-cart-sweep': typeof ApiPublicHooksAbandonedCartSweepRoute
  '/api/public/hooks/shipment': typeof ApiPublicHooksShipmentRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fragrance/$slug': typeof FragranceSlugRoute
  '/api/public/hooks/abandoned-cart-sweep': typeof ApiPublicHooksAbandonedCartSweepRoute
  '/api/public/hooks/shipment': typeof ApiPublicHooksShipmentRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fragrance/$slug': typeof FragranceSlugRoute
  '/api/public/hooks/abandoned-cart-sweep': typeof ApiPublicHooksAbandonedCartSweepRoute
  '/api/public/hooks/shipment': typeof ApiPublicHooksShipmentRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/fragrance/$slug'
    | '/api/public/hooks/abandoned-cart-sweep'
    | '/api/public/hooks/shipment'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/fragrance/$slug'
    | '/api/public/hooks/abandoned-cart-sweep'
    | '/api/public/hooks/shipment'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/fragrance/$slug'
    | '/api/public/hooks/abandoned-cart-sweep'
    | '/api/public/hooks/shipment'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FragranceSlugRoute: typeof FragranceSlugRoute
  ApiPublicHooksAbandonedCartSweepRoute: typeof ApiPublicHooksAbandonedCartSweepRoute
  ApiPublicHooksShipmentRoute: typeof ApiPublicHooksShipmentRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrance/$slug': {
      id: '/fragrance/$slug'
      path: '/fragrance/$slug'
      fullPath: '/fragrance/$slug'
      preLoaderRoute: typeof FragranceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/abandoned-cart-sweep': {
      id: '/api/public/hooks/abandoned-cart-sweep'
      path: '/api/public/hooks/abandoned-cart-sweep'
      fullPath: '/api/public/hooks/abandoned-cart-sweep'
      preLoaderRoute: typeof ApiPublicHooksAbandonedCartSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shipment': {
      id: '/api/public/hooks/shipment'
      path: '/api/public/hooks/shipment'
      fullPath: '/api/public/hooks/shipment'
      preLoaderRoute: typeof ApiPublicHooksShipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FragranceSlugRoute: FragranceSlugRoute,
  ApiPublicHooksAbandonedCartSweepRoute: ApiPublicHooksAbandonedCartSweepRoute,
  ApiPublicHooksShipmentRoute: ApiPublicHooksShipmentRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
